name: Release

on:
  push:
    tags:
      - "v*"


jobs:
  publish:
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: npm install -g pnpm
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - run: pnpm test && pnpm lint
        working-directory: js
      - uses: actions-rs/cargo@v1
        with:          
          command: publish
          # --allow-dirty needed for js/dist files
          args: --allow-dirty --token ${{ secrets.CARGO_TOKEN }}
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./js/package.json