[config]
skip_core_tasks = true


# Precommit
[tasks.precommit-cargo]
script = "cargo fmt && cargo clippy"

[tasks.precommit-js]
script = "cd js && graco fmt && graco commit-check"

[tasks.precommit.run_task]
name = ["precommit-js", "precommit-cargo"]


# Watch
[tasks.watch-cargo]
script = "cargo watch -x 'install --path . --debug --offline --features rust-editor --features source-map' -w src -w js/packages/quiz-embed/dist --ignore-nothing"

# [tasks.watch-js]
# script = "cd js && graco build -w"

[tasks.watch.run_task]
name = ["watch-cargo"]
parallel = true